service: chatr-service
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  stage: dev

  environment:
    JWT_SECRET: S3!
    VITE_API_BASE: https://qcgqjznbfg.execute-api.eu-west-2.amazonaws.com/dev

    MEMBERS_TABLE: chatr-members
    MESSAGES_TABLE: chatr-messages
    GROUPS_TABLE: chatr-groups
    READ_TRACKING_TABLE: chatr-read-tracking
    TYPING_TABLE: chatr-typing-status
    ATTACHMENTS_BUCKET: outsec-chat-bucket

    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

package:
  individually: true
  patterns:
    - "!frontend/**"
    - "!node_modules/**"
    - "src/**"
    - "package.json"

functions:
  auth:
    handler: src/handlers/auth.handler
    events:
      - http:
          path: auth
          method: POST
          cors: true

  register:
    handler: src/handlers/register.handler
    events:
      - http:
          path: auth/register
          method: POST
          cors: true

  members:
    handler: src/handlers/members.handler
    events:
      - http:
          path: members/{proxy+}
          method: ANY
          cors: true

  messages:
    handler: src/handlers/messages.handler
    events:
      - http:
          path: messages/{proxy+}
          method: ANY
          cors: true

  groups:
    handler: src/handlers/groups.handler
    events:
      - http:
          path: groups/{proxy+}
          method: ANY
          cors: true

  presignUpload:
    handler: src/handlers/presignUpload.handler
    events:
      - http:
          path: presign-upload
          method: POST
          cors: true

  presignDownload:
    handler: src/handlers/presignDownload.handler
    events:
      - http:
          path: presign-download
          method: POST
          cors: true

  typing:
    handler: src/handlers/typing.handler
    events:
      - http:
          path: typing/{proxy+}
          method: ANY
          cors: true
