service: chatr-service
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  stage: dev

  environment:
    JWT_SECRET: S3!

    MEMBERS_TABLE: chatr-members
    MESSAGES_TABLE: chatr-messages
    GROUPS_TABLE: chatr-groups
    READ_TRACKING_TABLE: chatr-read-tracking
    TYPING_TABLE: chatr-typing-status
    ATTACHMENTS_BUCKET: outsec-chat-bucket

    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

package:
  individually: true
  patterns:
    - "!frontend/**"
    - "!node_modules/**"
    - "src/**"
    - "package.json"

custom:
  corsConfig:
    origin: "*"
    headers:
      - Content-Type
      - Authorization
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
    allowCredentials: false

functions:
  auth:
    handler: src/handlers/auth.handler
    events:
      - http:
          path: auth
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

      - http:
          path: auth
          method: options
          cors: true

  register:
    handler: src/handlers/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: ${self:custom.corsConfig}

  members:
    handler: src/handlers/members.handler
    events:
      - http:
          path: members/{proxy+}
          method: any
          cors: ${self:custom.corsConfig}

  messages:
    handler: src/handlers/messages.handler
    events:
      - http:
          path: messages/{proxy+}
          method: any
          cors: ${self:custom.corsConfig}

  groups:
    handler: src/handlers/groups.handler
    events:
      - http:
          path: groups/{proxy+}
          method: any
          cors: ${self:custom.corsConfig}

  presignUpload:
    handler: src/handlers/presignUpload.handler
    events:
      - http:
          path: presign-upload
          method: post
          cors: ${self:custom.corsConfig}

  presignDownload:
    handler: src/handlers/presignDownload.handler
    events:
      - http:
          path: presign-download
          method: post
          cors: ${self:custom.corsConfig}

  typing:
    handler: src/handlers/typing.handler
    events:
      - http:
          path: typing/{proxy+}
          method: any
          cors: ${self:custom.corsConfig}
